//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public int TitleId { get; set; }
        public Nullable<int> PersonId { get; set; }
    
        public virtual Titles Titles { get; set; }
        public virtual People People { get; set; }
    }
}
